[tool.black]
line-length = 127
include = '\.pyi?$'
extend-exclude = '''
^/migrations/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 127
