[tool.black]
line-length = 127
include = '\.pyi?$'
extend-exclude = '''
^/migrations/
'''

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v -s --cov=src --cov-report=term-missing"
