[tool.black]
line-length = 127
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 127

[tool.pylint]
max-line-length = 127
disable = C0111,C0103
output-format = "colorized"
reports = "yes"

[tool.pytest]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=src --cov-report=term-missing"
