"""update_schema

Revision ID: 6009b63a280a
Revises: 28943d3dc459
Create Date: 2025-01-31 09:33:50.998629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6009b63a280a'
down_revision: Union[str, None] = '28943d3dc459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # インデックスが存在するかチェックして作成
    with op.batch_alter_table('categories') as batch_op:
        try:
            batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)
        except Exception:
            pass  # インデックスが既に存在する場合はスキップ


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.add_column('skill_assessments', sa.Column('proficiency_level', sa.INTEGER(), nullable=False))
    op.add_column('skill_assessments', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.add_column('skill_assessments', sa.Column('notes', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_skill_assessments_id'), table_name='skill_assessments')
    op.drop_column('skill_assessments', 'assessed_at')
    op.drop_column('skill_assessments', 'status')
    op.drop_column('skill_assessments', 'evidence')
    op.drop_column('skill_assessments', 'level')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.create_table('simple_models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
