name: Basic Test Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Debug Information
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Ubuntu version:"
          lsb_release -a

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Get repository content
        run: |
          git clone https://github.com/GingaDza/skill-matrix-manager.git .
          echo "Repository contents:"
          ls -la

      - name: Basic Python test
        run: |
          python --version
          python -c "print('Basic test successful')"
