name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Create working directory
      run: |
        pwd
        ls -la

    - name: Set up Python
      run: |
        sudo apt update
        sudo apt install -y python3.10 python3.10-venv python3-pip
        python3.10 -m venv venv
        source venv/bin/activate
        python --version

    - name: List repository contents
      run: |
        pwd
        ls -la
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "GITHUB_SHA: $GITHUB_SHA"
        echo "GITHUB_REF: $GITHUB_REF"

    # 最小限のテストから始める
    - name: Run basic test
      run: |
        source venv/bin/activate
        python -c "print('Basic test successful')"