name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      run: |
        git clone https://github.com/GingaDza/skill-matrix-manager.git .
        git checkout $GITHUB_SHA

    - name: Set up Python
      run: |
        sudo apt update
        sudo apt install -y python3.10 python3.10-venv python3-pip
        python3.10 -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8 black isort

    - name: Format with black
      run: |
        source venv/bin/activate
        black . --check

    - name: Check imports with isort
      run: |
        source venv/bin/activate
        isort . --check-only --diff

    - name: Lint with flake8
      run: |
        source venv/bin/activate
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests with coverage
      run: |
        source venv/bin/activate
        PYTHONPATH=$PYTHONPATH:. pytest --cov=src --cov-report=term-missing

    - name: Display test results
      if: always()
      run: |
        source venv/bin/activate
        echo "=== Test Results ==="
        echo "Coverage Report:"
        pytest --cov=src --cov-report=term-missing