name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment
      run: |
        pwd
        mkdir -p workspace
        cd workspace

    - name: Set up Python
      run: |
        sudo apt update
        sudo apt install -y python3.10 python3.10-venv python3-pip
        python3.10 -m venv venv
        source venv/bin/activate

    - name: Get repository content
      run: |
        cd workspace
        git clone https://github.com/GingaDza/skill-matrix-manager.git .
        git checkout $GITHUB_SHA

    - name: Install dependencies
      run: |
        cd workspace
        source venv/bin/activate
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        pip install pytest pytest-cov flake8 black isort

    - name: Run linting
      run: |
        cd workspace
        source venv/bin/activate
        black . --check
        isort . --check-only --diff
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run tests
      run: |
        cd workspace
        source venv/bin/activate
        PYTHONPATH=$PYTHONPATH:. pytest -v --cov=src --cov-report=term-missing

    - name: Report results
      if: always()
      run: |
        cd workspace
        echo "=== Test Results ==="
        echo "Working Directory:"
        pwd
        echo "Python Version:"
        python --version
        echo "Directory Contents:"
        ls -la